### ISSUE TITLE
After updating intellij idea components configuration resets to defaults

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#106]
Orginally described here: #59 
>Looks like I'm experiencing some similar issue. Whenever I update Android Studio or some other ?
>Plugin, all my custom mf tasks are reset to default settings and I have to reconfigure them…

**Comment by marcinsus** [comment]
I confirm this bug. Traces to reproduce:
1. Run Intellij, configure mainframer & inject to any configuration
2. Move to configuration and edit Mainframer Make inside before run tasks & save
3. Restart inteliJ
4. Custom Mainframer make has default values

**Comment by marcinsus** [comment]
In my case after apply update i have to invalidate all InteliJ data.
