### ISSUE TITLE
Separate default configuration for run configurations

### ISSUE THREAD

**Issue by jozzi05** [elpassion/mainframer-intellij-plugin#110]
As a user I would like to set a default mainframer before task for the specific run configuration. For example for all Android JUnit run configurations I would like to set mainframer before task with task name `aDAT` to assemble debug android tests.

Currently you can define only one default mainframer before tasks for all run configurations.

**Comment by ghostbuster91** [comment]
Not exactly. Defining a default `Mainframer Make` task is used only for injection. Probably it is more useful when u have one `Mainframer Make` across whole project. 
Still, after injection, you can modify manually `Mainframer Make` task for specific configuration, especially you can modify your `Mainframer  Make` task from `Android Junit` run configuration template. If you do that you will have proper task in each newly created `Android Junit` configuration, which is what you want, am I right?

Setting default `Mainframer Make` for specific run configurations during injection doesn't have much value for me and requires some additional development.

**Comment by jozzi05** [comment]
Indeed it works as you said. Then for me this task is redundant. I will archive it.
