### ISSUE TITLE
Release 1.0 stable

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#111]

**Comment by artem-zinnatullin** [comment]
Wait wait wait, can we try latest pre 0.x release for a week or so in our
team before releasing 1.x?

**Comment by ghostbuster91** [comment]
Ok, but in such case I would like to merge features which were planned for 1.1 but are already ready.

**Comment by artem-zinnatullin** [comment]
As you wish!
