### ISSUE TITLE
Default task requirement

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#116]
Don’t know anything about you guys, but I see a very little usage of the Default Task Name configuration option. Most of the time I will modify it when modifying a configuration. Maybe make it optional or remove it at all?
![screen shot 2017-03-14 at 16 16 07](https://cloud.githubusercontent.com/assets/200401/23902726/29cefba6-08d3-11e7-825d-077f8a1d44b8.png)

**Comment by artem-zinnatullin** [comment]
Yup, I have to put something like "-i" to fill it and then override per
each run config.

**Comment by pawegio** [comment]
1. Remove default task name
2. Make task name in *Mainframer Make* optional
3. Remove task name from general settings

**Comment by OrdonTeam** [comment]
I have removed task name from all plugin.
I didn't make sense to keep it optional. Is it easier to put task name at the end of build command.
