### ISSUE TITLE
Mainframer template

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#117]
Not sure if it is by intention, but there is a Mainframer template in the templates list.
<img width="324" alt="screen shot 2017-03-14 at 16 56 27" src="https://cloud.githubusercontent.com/assets/200401/23903961/5d177962-08d7-11e7-98fb-02cffd42a06b.png">

**Comment by ghostbuster91** [comment]
It is, but the real question is whether or not should we have mainframer configuration.

**Comment by pawegio** [comment]
After short discussion we decided to not forbid user doing anything even if it seems unreasonable for us. They might find a logical use case for injecting mainframer task to mainframer configuration template.
