### ISSUE TITLE
Run title

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#118]
Is it possible to change this title to something else, i. e. Mainframer or something? Not sure how it is handles by other tools.
<img width="209" alt="screen shot 2017-03-14 at 17 04 30" src="https://cloud.githubusercontent.com/assets/200401/23904302/6e30d904-08d8-11e7-812b-caba09567c1a.png">

**Comment by ghostbuster91** [comment]
I will change it for now to 'Mainframer'
