### ISSUE TITLE
Configuration default task

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#119]
Run → Edit Configurations → Mainframer shows empty fields. Not sure if it intentional.

**Comment by ghostbuster91** [comment]
It is. Configure mainframer in project action is connected with `Mainframer Make` tasks. The Mainframer run configuration is something different. It describes standalone job which can be  run via mainframer. Again do we need such thing?

**Comment by pawegio** [comment]
1. Configure mainframer in project action should be also applied to mainframer run/debug configuration template.
2. Update configuration dialog with additional info.
