### ISSUE TITLE
Parse errors from remote compilation and make them clickable

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#12]

**Comment by artem-zinnatullin** [comment]
They will be clickable, if path in log will be available on local machine.
One way is to do it through symlinks either on local or remote machine.

**Comment by ghostbuster91** [comment]
Symlinks.. Hmm, interesting, I will give a try.

**Comment by ghostbuster91** [comment]
I wasn't able to create a symlink on my local mac book machine. (The /home folder is somehow blocked). Maybe there is a way to do this, or like you said to create it on remote machine but still it requires additional steps to do for developers which I would like to avoid.

**Comment by ghostbuster91** [comment]
I think that we just need to attach a filter to console output
`com.intellij.execution.filters.RegexpFilter`

**Comment by jozzi05** [comment]
Yes, this the only way to have this feature.
But until this feature is not implemented I highly recommend to use `awesomeConsole` intelij plugin. It basically do what we want.
