### ISSUE TITLE
Plugin icon visibility

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#122]
When taking a look at the plugins list using the Tools menu icon is kind of not visible on the macOS.
<img width="307" alt="screen shot 2017-03-14 at 17 24 25" src="https://cloud.githubusercontent.com/assets/200401/23905173/4289a134-08db-11e7-9ec7-a4bd3d9d43e5.png">

**Comment by pawegio** [comment]
I prepared two (temporary) icons: one for light theme ([blue](https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/resources/icons/mainframerIcon%402x.png)) and another one for darcula ([white](https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/resources/icons/mainframerIcon%402x_dark.png)). I'm using dark tool menu on the macOS & darcula theme in IntelliJ IDEA and icon looks fine everywhere.

![zrzut ekranu 2017-03-14 o 23 54 07](https://cloud.githubusercontent.com/assets/876573/23925860/896c12ae-0911-11e7-9ba7-1181ae780898.png)

**Comment by artem-zinnatullin** [comment]
Nice!

**Comment by ming13** [comment]
Yep, I agree. But isn’t that still an issue though?

**Comment by pawegio** [comment]
It is. We can create new icons set or replace white one to improve visibility on light background.
