### ISSUE TITLE
Don't show run bubble when tool window is visible

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#123]
When starting a mainframer-configured task there is a green bubble on the bottom. As far as I know it is only shown when the tools windows was hidden. For example, if you start a long test running task and hide the tool window it will show a bubble after it is finished.

**Comment by pawegio** [comment]
AFAIK, this is how IntelliJ works.

**Comment by ming13** [comment]
Sorry if I wasn’t clear. As I see it the bubble should be shown only when the tool window is hidden. At this point it is always shown on every run, no matter the window state.

**Comment by jozzi05** [comment]
Our team members mentioned this bubble is being shown too often and to be honest it is redundant. We are going to remove it.

**Comment by jozzi05** [comment]
CR:
1. Remove bubble.
