### ISSUE TITLE
Configuration task name is being reset

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#127]
1. Tools → Mainframer → Configure.
2. Default build command: `./gradlew`. Default task name: `-i`.
3. Run → Edit Configurations.
4. `+` → Android App.
5. Before Launch → Mainframer Make.
5. Task name: `assembleDebug`.
6. Android Studio → Quit Android Studio.
7. Open Android Studio.
8. Run → Edit Configurations.
9. Created above configuration → Mainframer Make → Edit.
10. Task name: `-i`. Should be: `assembleDebug`.

**Comment by jozzi05** [comment]
Task name will be removed (Please refer to #116) in next version of plugin. I will no longer investigate this bug. If new problem related to this bug occurs, feel free to create new issue.
