### ISSUE TITLE
Before launch task window title

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#128]
1. Run → Edit Configurations
2. Choose a configuration.
3. Before launch → Mainframer Make → Edit.
4. Window title is empty.
![screen shot 2017-03-16 at 10 16 06](https://cloud.githubusercontent.com/assets/200401/23985714/9830a464-0a31-11e7-87ca-7131a2f2f160.png)

**Comment by jozzi05** [comment]
AC:
1. Add title "Configure Mainframer Make"

**Comment by OrdonTeam** [comment]
Add missing test

**Comment by jozzi05** [comment]
After some research I wasn't able to create unit test for title.
