### ISSUE TITLE
Tools menu items naming

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#135]
Just proposing to rename options to be shorter.

* Tools → Mainframer → Configure Mainframer in Project
  * Configure for Project
* Tools → Mainframer → Select configurations to inject mainframer or restore default
  * Inject to Configurations

**Comment by jozzi05** [comment]
AC:
1. Change name "Configure Mainframer in Project" to "Configure for Project"
2. Change name "Select configurations to inject mainframer or restore default" to "Inject or restore configurations"

**Comment by jozzi05** [comment]
@ming13 It's very easy to introduce this changes and we currently have limited resources to develop open-source projects. We are also opened to merge Pull Requests, feel free to create one in free time :)

**Comment by ming13** [comment]
Sure thing. Just curious — can we move all UI strings to `.properties`? Seems like other plugins using it, but I’m not sure how to fetch these values from source code.

**Comment by OrdonTeam** [comment]
Yes we can extract UI strings to .properties. It sounds like a good change. Feel free to introduce it.

**Comment by jozzi05** [comment]
Indeed it is a good change, but for me it's separate task.

**Comment by jozzi05** [comment]
I created a separate task for extracting string resources. Please refer to: #138
