### ISSUE TITLE
Mainframer toolbar button execution

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#136]
I have noticed a thingy when disabling Mainframer via the toolbar button.

The build command without Mainframer is executed as a following command.
```
bash "./gradlew tasks" 
```
This will not work, it requires `-c` argument.
```
bash -c "./gradlew tasks" 
```

**Comment by artem-zinnatullin** [comment]
I wanted to fix this, but GitHub search found two very similar files and I'm not sure where should we propose a fix (I guess opening project in IDE could help, but I'm on pretty slow pc right now):

* [common/mfCommandLineProvider.kt](https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/kotlin/com/elpassion/mainframerplugin/common/mfCommandLineProvider.kt)
* [common/console/mfCommandLineProvider.kt](https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/kotlin/com/elpassion/mainframerplugin/common/console/mfCommandLineProvider.kt)

**Comment by OrdonTeam** [comment]
Fixed duplicated file in fe77651bbc4fb3287b70d6c396a895b53a1949ec.
[common/console/mfCommandLineProvider.kt](https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/kotlin/com/elpassion/mainframerplugin/common/console/mfCommandLineProvider.kt) is the one I left.

**Comment by artem-zinnatullin** [comment]
Thanks! Then @ming13 or I will post a fix for `bash -c`
