### ISSUE TITLE
Mainframer naming

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#144]
I can see [some differences in naming](https://github.com/elpassion/mainframer-intellij-plugin/blob/3645a6ecfe4f31f64e3fb5ea8e82758e32bdbad3/src/main/kotlin/com/elpassion/mainframerplugin/action/configure/MFConfigureProjectActionController.kt#L26-L28) in UI at this point.

Actually we are kind of split on that :-) @artem-zinnatullin prefers `mainframer`, I tend to use `Mainframer` for its convenience in text without special formatting, i. e. Markdown, because it kind of blends in in such cases.

@artem-zinnatullin, what do you think? I vote for using Mainframer everywhere.

**Comment by artem-zinnatullin** [comment]
Oh God, let's stick to Mainframer I guess
