### ISSUE TITLE
Console should break long lines

### ISSUE THREAD

**Issue by macPry** [elpassion/mainframer-intellij-plugin#153]

**Comment by pawegio** [comment]
Isn't it built-in console view?

<img width="131" alt="zrzut ekranu 2017-05-18 o 16 45 32" src="https://cloud.githubusercontent.com/assets/876573/26208132/a38d1844-3be9-11e7-9079-cd66ca6f04ab.png">

**Comment by ghostbuster91** [comment]
Yes, you are right.
