### ISSUE TITLE
Consider asynchronous idea sync after mainframer task execution.

### ISSUE THREAD

**Issue by igor-korotenko** [elpassion/mainframer-intellij-plugin#16]
Common issue with IntelliJ IDEA, that we are experiencing while developing using `mainframer` is when you press "Debug selected configuration" while some particular test configuration selected, compile tests on remote machine, sync it back, then idea runs new test classes and don't mind about breakpoint there. @artem-zinnatullin think that this can be because of asynchronous sync of idea cache after external task invocation. Adding `sleep 2` task after main test task fixes it in most of cases. This can be more general issue, this is only example of such kind of behavior.

**Comment by ghostbuster91** [comment]
I think we need to call ` VirtualFileManager.getInstance().refresh( false )` but let me check it.

**Comment by igor-korotenko** [comment]
@ghostbuster91 ok, thank you!
