### ISSUE TITLE
Bring back support for 2.x version

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#169]
Lack of it prevents us from deploying new version.
We have to distinguish between released artefacts and for pre 3.0 versions we should add `.sh` extension to the download url.

**Comment by pawegio** [comment]
This concerns https://github.com/gojuno/mainframer/issues/169

**Comment by artem-zinnatullin** [comment]
Can we support both `mainframer.sh` and `mainframer` in one version? We don't have other incompatible changes in 3.x so far.

Sorry for that guys :(

**Comment by ghostbuster91** [comment]
Yes, that's the plan :) 

No problem @artem-zinnatullin We should have make it like that from the beginning.
