### ISSUE TITLE
Add macros support

### ISSUE THREAD

**Issue by neworld** [elpassion/mainframer-intellij-plugin#170]
Mine project has a lot of flavors and I have hard to work with them. Often I set one flavor in IDE, but build another by accident. One solution what would work for me could be macros for `build command`.

![image](https://user-images.githubusercontent.com/38703/29658406-622694b2-88c3-11e7-9ba5-0650aa3f7b50.png)

I could use 
```diff
-./gradlew appl:compileGlobalDebugUnitTestSources -PminSdk=23
+./gradlew appl:compile$Flavor$UnitTestSources -PminSdk=23
```

However, there could be more Macros, like as `External tools`:

![image](https://user-images.githubusercontent.com/38703/29658572-060071e8-88c4-11e7-87d9-cb1a0243d03c.png)

**Comment by edwardstock** [comment]
@neworld Did you try this think? https://github.com/gojuno/mainframer/issues/49
Look at idea xml (or iml) files, there's much information that you can extract for your needs.
Than just create bash script and at idea plugin set build command: `/path/to/mainframer.sh ./my-remote-build.sh`

For example, my build command:
```bash
#!/bin/bash
MODULE_NAME="app" # you can use bash args to choose module name
ASSEMBLE_TASK_NAME=$(xmllint --xpath "string(//option[@name='ASSEMBLE_TASK_NAME']/@value)" ${MODULE_NAME}/${MODULE_NAME}.iml)
COMMAND_LINE_OPTIONS=$(xmllint --xpath "string(//option[@name='COMMAND_LINE_OPTIONS']/@value)" .idea/workspace.xml)

echo -e "Build flavor: ${ASSEMBLE_TASK_NAME}"
echo -e "Compiler options: ${COMMAND_LINE_OPTIONS}"

./gradlew :${MODULE_NAME}:${ASSEMBLE_TASK_NAME} ${COMMAND_LINE_OPTIONS} -Pandroid.enableBuildCache=true
```

**Comment by ghostbuster91** [comment]
Hi @edwardstock, @neworld 
Thank you for your input. I think it would be very beneficial to incorporate it into plugin. I will try to do this in the nearest future.
Of course PRs are welcome.

**Comment by ghostbuster91** [comment]
Ok so it looks definitely doable :) 
There is a class `MacroManager` and it has a method `expandMacrosInString` which requires `dataContext` which we get from `taskProvider` in `execute` method.

From the gui perspective we have to use `MacrosDialog` and do sth similar to following:
```
MacrosDialog dialog = new MacrosDialog(myProject);
      if (dialog.showAndGet() && dialog.getSelectedMacro() != null) {
        String macro = dialog.getSelectedMacro().getName();
        int position = myTextField.getCaretPosition();
        try {
          myTextField.getDocument().insertString(position, "$" + macro + "$", null);
          myTextField.setCaretPosition(position + macro.length() + 2);
        }
        catch (BadLocationException ignored) {
        }
      }
      IdeFocusManager.findInstance().requestFocus(myTextField, true);
```

**Comment by neworld** [comment]
@edwardstock, I working on the large project with a lot of build configurations. That script could be better but doesn't solve my problem.

@ghostbuster91, Thanks for approving the idea. Maybe I will make a PR by myself
