### ISSUE TITLE
Android Studio 3.1 is not supported

### ISSUE THREAD

**Issue by neworld** [elpassion/mainframer-intellij-plugin#184]
Android Studio 3.1 is built on `173.4670197`, but plugin latest supporting version is `173.4301.14`

**Comment by pawegio** [comment]
It should be fixed in https://github.com/elpassion/mainframer-intellij-plugin/pull/183. Update should be available soon.

**Comment by neworld** [comment]
Thanks for the super fast release! Everything is working
