### ISSUE TITLE
Android Studio 3.1.1 adds Gradle-aware Make to Android run configuration

### ISSUE THREAD

**Issue by anton-novikau** [elpassion/mainframer-intellij-plugin#185]
All Android Run configuration get patched on every IDE restart with the default Before launch tasks starting with release of Android Studio 3.1.1. According to release notes it was done on purpose.

> **3.1.1 (April 2018)**
> In some cases, when a project created in Android Studio 3.0 was opened for the first time in Android Studio 3.1, the Gradle-aware Make task was removed from the Before launch area in Run/Debug Configurations. The result was that projects did not build when the Run or Debug button was clicked, which in turn caused failures such as deployment of incorrect APKs and crashes when using Instant Run.
>
> To solve this problem, Android Studio 3.1.1 adds the Gradle-aware Make task to the run configuration for projects that are missing this entry. This modification occurs after the first Gradle sync when the project is loaded.

For Mainframer powered tasks there is no need in Gradle-aware Make task in Before launch area. Every time I start Android Studio I have to go to Run configuration and remove this task to make my builds fast again. 

If this is a common issue of all Mainframer users I wanted to suggest to add a feature to the plugin: 

_Check the state of the Android Run configurations and remove Gradle-aware Make form their Before Launch area if there is Mainframer Make task defined (these two tasks usually do the same, so I don't see why they should be used both)._

I'm not good in IntelliJ Idea plugin development so I don't really know if 3d party plugins have a permission to edit Run Configurations or read their current state. So if it is not possible to implement just let me know and close the issue.

If anyone knows a simple workaround for this issue that doesn't require changes in the plugin please share your wisdom.

Thanks.

**Comment by vibinr** [comment]
You can fix this by adding a flag in your Studio's vm options file: https://issuetracker.google.com/issues/77840239#comment3

**Comment by ming13** [comment]
I guess Viber uses Mainframer ;-)

It is actually an Android Studio issue, just like @vibinr mentioned earlier. I was under an impression that it was changed in AS 3.2 but I haven’t tested it yet.

At the same time, I think it is a totally valid usecase to customize your Run Configurations as you please and even have Gradle-aware Make thingy with Mainframer. At least we shouldn’t block this ability.

On other hand, the reason why Android Studio does that force-adding is beyond me. IntelliJ IDEA worked with Configurations for years. I think we should put a comment on the issue. Plus, @artem-zinnatullin is going to ask this exact question on I/O.

**Comment by ghostbuster91** [comment]
@anton-novikau Plugins can easily customize run configurations. We already do that in our code, see: https://github.com/elpassion/mainframer-intellij-plugin/blob/develop/src/main/kotlin/com/elpassion/mainframerplugin/action/select/TaskManipulator.kt#L37

What **might** be problematic here is the order of execution. We have to execute our code after Android Studio does, which might requires registering into android studio specific extensions. At this point we don't have android-studio specific features, but it doesn't mean that we can't have (Of course in a separate module).

**Comment by anton-novikau** [comment]
> You can fix this by adding a flag in your Studio's vm options file: https://issuetracker.google.com/issues/77840239#comment3

@vibinr Than you very much! You saved me from getting crazy :)

**Comment by anton-novikau** [comment]
> I guess Viber uses Mainframer ;-)

@ming13 we actually do because it is awesome! So thank you guys for the this life saving tool.

> It is actually an Android Studio issue

I understand that this is an Android Studio issue. That's why I quoted release notes from v3.1.1. The reason why I decided to open the issue in Mainframer plugin's repository is that 

- It could affect all Mainframer users
- Android Studio developers, most probably, are not aware of the Mainframer tool and fix their own bugs by adding Gradle-aware Make task to all Run configurations
- Plugin is the only place where we have access to Run configurations of IDE where the fix could be applied. 

> @artem-zinnatullin is going to ask this exact question on I/O

Actually I thought to ask the same question on I/O Office Hours too, but I/O is only in a week and I couldn't get used to this self-restoring tasks.

**Comment by anton-novikau** [comment]
> @anton-novikau Plugins can easily customize run configurations

@ghostbuster91 thank you! Since there is a simple workaround I'll stick on it. I'm not sure it makes sense implementing the feature I suggested, since even Android Studio developers consider restoring Gradle-aware Make task as a workaround and I hope they will drop it in one of the future version.

**Comment by ming13** [comment]
FYI — I’ve received some clarification at the [Google issue](https://issuetracker.google.com/issues/77840239#comment4). 

I’m still interested in the reasoning behind `Gradle-aware Make` step existence and its difference from the native IJ `Build` one. Hopefully @artem-zinnatullin will solve this for us with the Tooling team.

**Comment by artem-zinnatullin** [comment]
Yeah, ideally AS would only call `gradlew` or `gradle` binary, but unfortunately they rely on Gradle Tooling API heavily.

For example, IntelliJ Buck Plugin just calls `buck` or `buckw` binary (we use wrapper) and we're able to do lots of stuff by modifying `buckw`.
