### ISSUE TITLE
Doesn't work in IntelliJ Ultimate 2019.1 and in Android Studio 3.5

### ISSUE THREAD

**Issue by febs** [elpassion/mainframer-intellij-plugin#191]
I can't find the mainframer plugin in the now called "plugin marketplace", and if I try to install it from disk I get the error message complaining that the plugin 'is incompatible with this installation'

![image](https://user-images.githubusercontent.com/604435/55826762-ff252080-5b08-11e9-9c03-89c033e95b35.png)

**Comment by JayNewstrom** [comment]
I've not worked on intellij plugins before, but this is pretty crucial to my workflow. Could someone point me in the right direction? I'd be willing to spend the time to fix this.

**Comment by JayNewstrom** [comment]
1.2.9 fixed the issue for me.

**Comment by pawegio** [comment]
I've added support for IJ 2019.1 and AS 3.5 in version **1.2.9**. Please check it out.
