### ISSUE TITLE
Not supported ufter updating to Android Studio 3.6.0

### ISSUE THREAD

**Issue by amperas171** [elpassion/mainframer-intellij-plugin#193]
<img width="439" alt="Снимок экрана 2020-03-06 в 18 38 11" src="https://user-images.githubusercontent.com/29694475/76107626-21117680-5fea-11ea-83f2-88b23b7b49d6.png">

**Comment by neworld** [comment]
I made a fix for it: #194. @pawegio, could you release an updated version?

**Comment by marsounjan** [comment]
seems like 1.2.10 is still not released...

**Comment by marsounjan** [comment]
@pawegio ^^ ? :)
