### ISSUE TITLE
Add validation to edit task in configuration

### ISSUE THREAD

**Issue by marcinsus** [elpassion/mainframer-intellij-plugin#41]

**Comment by ghostbuster91** [comment]
Can you provide some description ? What's wrong with current impl?

**Comment by marcinsus** [comment]
@ghostbuster91 At this moment you can write invalid values during edit current task configuration.

**Comment by ghostbuster91** [comment]
Please fix validation order

**Comment by marcinsus** [comment]
@ghostbuster91 Already done by unify validation logic.
