### ISSUE TITLE
Can't run mainframer before task

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#43]

**Comment by ghostbuster91** [comment]
bash: /Users/elpassion/IntelliJIDEAProjects/MyApplication/mainframer.sh ./gradlew assembleDebug: No such file or directory

**Comment by artem-zinnatullin** [comment]
We're seeing this as well whenever you click on run button that is on the
left of the code (test or main function for instance), funny thing is that
if you then launch configuration, created by your click, by clicking cmd +
R or by clicking on it in run config menu it'll work normally.

**Comment by OrdonTeam** [comment]
Tests are testing concrete implementation rather than behaviour

**Comment by pawegio** [comment]
@OrdonTeam applied in #32
