### ISSUE TITLE
As a user I want to be asked for server configuration while configuring mf in project

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#53]

**Comment by ghostbuster91** [comment]
Fix incorrect error msg when remote machine name is empty

**Comment by marcinsus** [comment]
I suggest to allow choose the path where mainframer script will be saved (default path still be project dir). @pawegio what do you think of it?

**Comment by pawegio** [comment]
Having default path of mainframer script sounds nice.
