### ISSUE TITLE
Custom MF task is not saved when startup inject enabled

### ISSUE THREAD

**Issue by marcinsus** [elpassion/mainframer-intellij-plugin#59]
We gave user ability to edit task parameter such as build command and script path. Unfortunately, because of MF startup script none of these fields are saved when you restart the project.

**Comment by ghostbuster91** [comment]
Could you please provide some better description and name for this task?

**Comment by marcinsus** [comment]
Done.

**Comment by ghostbuster91** [comment]
> We gave user ability to edit task parameter such as build command and script path. Unfortunately, because of MF startup script none of these fields are saved when you restart the project.

They are, but they become override. Please be specific.
I agree that's an issue.

**Comment by ghostbuster91** [comment]
During injection we need to ask user whether or not they want to override mainframer make tasks

**Comment by artem-zinnatullin** [comment]
Looks like I'm experiencing some similar issue. Whenever I update Android Studio or some other Plugin, all my custom mf tasks are reset to default settings and I have to reconfigure them…

**Comment by marcinsus** [comment]
@artem-zinnatullin 
Can you provide more details (Android Studio and AS MF plugin versions). Do you have checked MF setting "inject on startup"? What do you mean by default settings, it is from Android Studio ->Preferences->Mainframer?

**Comment by artem-zinnatullin** [comment]
```
Android Studio 2.3 RC 1
Build #AI-162.3742087, built on February 16, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

MF Plugin 0.2.3, I don't see "inject on startup" but "Configure before task on startup" is unchecked.
