### ISSUE TITLE
MainframerBeforeRunTaskProfile tab disappears on completion

### ISSUE THREAD

**Issue by artem-zinnatullin** [elpassion/mainframer-intellij-plugin#64]
Once `mainframer.sh` exits, tab with log disappears from IDE views. 

I was able to pin it somehow and now it does not disappear, but would be nice to do it by default :)

**Comment by artem-zinnatullin** [comment]
Wanted to notice that in order to pin it, I had to do something using mouse cursor real quick since most of the time `mainframer` invocations in our project take less than 10 seconds :)

**Comment by ghostbuster91** [comment]
Do you have any example in Intellij Idea of behaviour you would like to have?

**Comment by artem-zinnatullin** [comment]
If I run mf via External Tool invocation it does not go away from tabs list after mf exit and you can always click on it and check log output.

Another example is when you run regular tests or app config IntelliJ will show tab with logs and you can always navigate to them and check log output even if you have switched to some other view like Logcat.

**Comment by ghostbuster91** [comment]
Ok I did some investigation, it looks like we are overriding our window because of use of `DefaultRunExecutor`. We need to implement our custom one and override `getToolWindowId`
