### ISSUE TITLE
Rename "MainframerBefore" task name

### ISSUE THREAD

**Issue by pawegio** [elpassion/mainframer-intellij-plugin#73]
I think we should rename mainframer before launch task to provide more formal and specific description of "what it does?".

My proposals:
* Run with Mainframer
* Run Mainframer task
* Mainframer Make

**Comment by ghostbuster91** [comment]
You mean description or class?

**Comment by pawegio** [comment]
I mean task name/description in run configuration window.

**Comment by ghostbuster91** [comment]
Mainframer make sounds good to me

**Comment by artem-zinnatullin** [comment]
`Mainframer make` sounds like it'll build mainframer itself…

I'd vote for `Run with/through/via mainframer` cc @ming13, if our opinion counts :)

**Comment by ming13** [comment]
Default task name is `Gradle-aware Make` or `Make` depending on its type. In this context `Mainframer Make` makes more sense — just from consistency standpoint.

**Comment by pawegio** [comment]
Of course your opinion counts :) As @ming13 noticed we are replacing default `Gradle-aware Make`.

**Comment by artem-zinnatullin** [comment]
Yup, makes sense now!
