### ISSUE TITLE
Ask user for configurations to which mainframer will be applied

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#80]

**Comment by pawegio** [comment]
I separated UI part to task #84

**Comment by pawegio** [comment]
It's a parent task with following children:
- Dialog (UI part) in #84
- Dialog result in #89
- Injection taking proper result in #86

**Comment by ghostbuster91** [comment]
It doesn't work.

**Comment by marcinsus** [comment]
@ghostbuster91 injection just done on task #93
