### ISSUE TITLE
MFBeforeRunTaskProfile tab takes focus on each output change and brings itself to foreground

### ISSUE THREAD

**Issue by artem-zinnatullin** [elpassion/mainframer-intellij-plugin#85]
If I run some run configuration via mf plugin, and then hide its tab to continue work on code or open other tab, mf tab will bring itself to foreground each time something new appears in its output.

Environment: 

```
Mainframer Plugin: v0.2.3
Android Studio 2.3 Beta 4
Build #AI-162.3715353, built on February 8, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by marcinsus** [comment]
In my case after apply update i have to invalidate all InteliJ data.
